### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by rainerhahnekamp** [RefugeesCodeAT/hackboard#1]
Modify the landing page that represents us

**Comment by AlexHartveld** [comment]
Refinement: 
As a user, I need to understand the goal of the site in to read five words that can explain why this site exists. Maybe I can phrase it in such a way that even my parents could understand it. for example "Find a project team."
As a new user I want to see a first page page that explains to me about the functionality (for now, just that there's an overview and that I can add a project.)
As a new user I want to see a visually appealing first page. An image of a past Hackathon would be nice, to get me in the mood. Maybe even a slider of multiple images? 
As an interested developer I'd like to see a small link to the project on GitHub at the bottom of the page.

**Comment by HosamAlmoghraby** [comment]
the only dependency to do this page to have the photo on side, github and refugeescode icons.

![landing page](https://user-images.githubusercontent.com/32025281/39424074-2eb60b82-4c75-11e8-8cc9-02b9bcd2079b.png)

**Comment by HosamAlmoghraby** [comment]
I have removed the route and rebuilt it in a different way, I would like to have a feedback for my method
