### ISSUE TITLE
Controller with 5 Functions

### ISSUE THREAD

**Issue by rainerhahnekamp** [RefugeesCodeAT/hackboard#10]
* Return a list of all projects
* return the detail data of a project
* Remove a project
* Edit a project
* Add a project

**Comment by Thaerohde** [comment]
DOD: when we can :
    Return a list of all projects
    return the detail data of a project
    Remove a project
    Edit a project
    Add a project
Estimated: Small.
Done

**Comment by rainerhahnekamp** [comment]
So I would define the urls more towards a REST style like in https://gist.github.com/odan/1d2ef018adb3ea5a0d3abb35406d2c65#http-methods.
So
* GET List: /projects
* GET View: /projects/{projectId}
* PUT Edit: /projects/{projectId}
* DELETE Delete: /projects/{projectId}
* POST Add: /projects

You can add the '/projects' directly to the `@RestController`. So you don't have to repeat it in each function. Please mind that the same url acts differently depending on the html method.
