### ISSUE TITLE
Database seeding

### ISSUE THREAD

**Issue by rainerhahnekamp** [RefugeesCodeAT/hackboard#13]
Some example projects that are already included in the development database once Spring starts.

Some data: http://refugeescode.at/p2

**Comment by rainerhahnekamp** [comment]
@MohamedDahman you should find a way to do it with liquibase.

First of all liquibase is our central tool responsible for executing all ddl commands. So it is quite fitting that it also does the dml part.
Secondly reading a file from the resources folder will not work in the way you have written it once the application is packed into a jar.

**Comment by Thaerohde** [comment]
DOD: Providing the APP with a starting data.
Dependencies : Database , Dummy Data.
Estimated: L

**Comment by rainerhahnekamp** [comment]
Can you please create an own file for that?

The reaon is that I want to have the inserts separated from the creations. When it comes to live deployment there is an option in liquibase where we can ignore these changesets. Of course we don't want to have this test data in a production system. (Not even talking about the default users with their passwords).
