### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by rainerhahnekamp** [RefugeesCodeAT/hackboard#2]
create logo

**Comment by AlexHartveld** [comment]
Refinement: 
Task: Logo required as a favicon.ico. And probably in some other formats as well for placement on the landing page. Potential changes in color could come in handy as well. (The Sketch training may come in handy for this)

**Comment by HosamAlmoghraby** [comment]
![hackboard_logo](https://user-images.githubusercontent.com/32025281/39424182-a845485a-4c75-11e8-9a5b-803576aebc22.png)

**Comment by HosamAlmoghraby** [comment]
Orange Hex: E78200
Dark Blue Hex: 01233F
White Background Hex: FFFFFF

**Comment by rainerhahnekamp** [comment]
can we also have a quadratic logo.png version to replace the one in `webpack/logo-jhipster`?

**Comment by HosamAlmoghraby** [comment]
Check out "hackboard". https://color.adobe.com/hackboard-color-theme-10789493/

favicon done
logo dimensions fixed
