### ISSUE TITLE
Project module

### ISSUE THREAD

**Issue by rainerhahnekamp** [RefugeesCodeAT/hackboard#36]
DOD: Move all project related components into an own module. Currently it is in account.
Estimated: M

**Comment by HosamAlmoghraby** [comment]
Done..

**Comment by rainerhahnekamp** [comment]
* Please prefix the component with project. So instead of just ViewComponent, rename it to ProjectViewComponent. Even if it is already in the module project.
* We only need one module for projects. You have created a module for each component. That is not necessary.
* Concerning routing configuration there is nothing to do at the moment. Perhaps we will refactor it later. Just for info.

**Comment by rainerhahnekamp** [comment]
Points I have mentioned in my comment above are still open

**Comment by HosamAlmoghraby** [comment]
I did the first and the second points, which ones you mean still opened?

Thanks

**Comment by rainerhahnekamp** [comment]
1. The file and folder names need to be adapted. So it should be folder project-add and the files project-add.component.ts and so on.
2. The module file have to be deleted: list-routing.module.ts, edit-routing.module.ts, etc.
