### ISSUE TITLE
Detail Page of Project

### ISSUE THREAD

**Issue by rainerhahnekamp** [RefugeesCodeAT/hackboard#4]
Showing the details of the project without a form. There will be a button where the user can edit the project and is redirected to the edit project page.

**Comment by AlexHartveld** [comment]
Bootstrap Buttons may be useful with Glyphicons. 

And List Groups. They can just be non-functional buttons for now. 

![mobile portrait detail view](https://user-images.githubusercontent.com/7138601/39390635-c4d4755c-4a97-11e8-89eb-772935cd7296.png)

**Comment by rainerhahnekamp** [comment]
You have to make use of the endpoints instead of showing static data. I also see that you have removed the endpoint request in the project listings page. Therefore we have there again only static data.

**Comment by Farah7Tawfeek** [comment]
Sorry , I  am so confused about the endpoint request , it's not clear .

**Comment by rainerhahnekamp** [comment]
Take a look at the project add component and how I call the endpoint there and then just compare it with the code that you have commented in the list component. It was already working.
