### ISSUE TITLE
define the basics colour in global.scss

### ISSUE THREAD

**Issue by Farah7Tawfeek** [RefugeesCodeAT/hackboard#44]

**Comment by rainerhahnekamp** [comment]
Very nice, but can you move all the individual styles from hackboard to an own file called `global-hackboard.scss` for example and import that file in the `global.scss`? By that, we make sure that the pre-defined styling rules are separated from ours.

**Comment by Farah7Tawfeek** [comment]
okay .

**Comment by Farah7Tawfeek** [comment]
Done
